/* === CLIENTS === */
function rCl(C){
  const a=gd(K.cl);
  C.innerHTML='<div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6"><div class="relative flex-1 max-w-xs"><i class="fas fa-search absolute left-3 top-1/2 -translate-y-1/2 text-muted text-sm"></i><input class="ip pl-9" placeholder="Rechercher..." oninput="ft(\'cr\',this.value)"></div><button class="b bp" id="btn-new-cl"><i class="fas fa-plus"></i> Nouveau client</button></div><div class="cd overflow-x-auto">'+(a.length?'<table><thead><tr><th>Nom</th><th>Entreprise</th><th>Email</th><th>Telephone</th><th class="text-right">Actions</th></tr></thead><tbody>'+a.map(c=>'<tr class="cr" data-s="'+(c.nom+' '+(c.entreprise||'')+' '+(c.email||'')).toLowerCase()+'"><td class="font-medium cursor-pointer hover:text-accent" data-act="view" data-id="'+c.id+'">'+c.nom+'</td><td class="text-muted">'+(c.entreprise||'-')+'</td><td class="text-muted">'+(c.email||'-')+'</td><td class="text-muted">'+(c.tel||'-')+'</td><td class="text-right"><button class="b bs sm" data-act="edit" data-id="'+c.id+'"><i class="fas fa-pen"></i></button> <button class="b bd sm" data-act="del" data-id="'+c.id+'"><i class="fas fa-trash"></i></button></td></tr>').join('')+'</tbody></table>':'<div class="es"><i class="fas fa-users block"></i>Aucun client.<br><button class="b bp mt-4" id="btn-new-cl2"><i class="fas fa-plus"></i> Creer un client</button></div>')+'</div>';
  C.querySelector('#btn-new-cl')?.addEventListener('click',()=>rClF());
  C.querySelector('#btn-new-cl2')?.addEventListener('click',()=>rClF());
  C.querySelectorAll('[data-act="view"]').forEach(e=>e.onclick=()=>nav('clients',{id:e.dataset.id}));
  C.querySelectorAll('[data-act="edit"]').forEach(e=>e.onclick=()=>rClF(e.dataset.id));
  C.querySelectorAll('[data-act="del"]').forEach(e=>e.onclick=()=>cfm('Supprimer ?','Action irreversible.',function(){sd(K.cl,gd(K.cl).filter(x=>x.id!==e.dataset.id));toast('Supprime','success');render()}));
}
function rClF(id){
  const c=id?gd(K.cl).find(x=>x.id===id):null;
  document.getElementById('ptitle').textContent=c?'Modifier le client':'Nouveau client';
  const C=document.getElementById('ct');
  C.innerHTML='<div class="max-w-2xl"><button class="b bs mb-4" id="back"><i class="fas fa-arrow-left"></i> Retour</button><div class="cd"><form id="clf"><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><div><label>Nom *</label><input class="ip" name="nom" required value="'+(c?.nom||'')+'"></div><div><label>Entreprise</label><input class="ip" name="entreprise" value="'+(c?.entreprise||'')+'"></div><div><label>Email</label><input class="ip" name="email" type="email" value="'+(c?.email||'')+'"></div><div><label>Telephone</label><input class="ip" name="tel" value="'+(c?.tel||'')+'"></div></div><div class="mb-4"><label>Adresse</label><textarea class="ip" name="adresse" rows="2">'+(c?.adresse||'')+'</textarea></div><div class="mb-6"><div class="text-xs text-muted uppercase tracking-wider mb-2"><i class="fas fa-qrcode mr-1"></i>Adresse structuree (optionnel, requise pour la QR-facture)</div><div class="grid grid-cols-1 md:grid-cols-4 gap-3 mb-3"><div class="md:col-span-2"><label>Rue</label><input class="ip" name="rue" value="'+(c?.rue||'')+'"></div><div><label>N&deg;</label><input class="ip" name="rueNo" value="'+(c?.rueNo||'')+'"></div><div><label>NPA</label><input class="ip" name="npa" value="'+(c?.npa||'')+'"></div></div><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label>Ville</label><input class="ip" name="ville" value="'+(c?.ville||'')+'"></div><div><label>Pays</label><input class="ip" name="pays" maxlength="2" style="text-transform:uppercase" value="'+(c?.pays||'CH')+'"></div></div></div><div class="mb-6"><label>Notes</label><textarea class="ip" name="notes" rows="3">'+(c?.notes||'')+'</textarea></div><div class="flex gap-3"><button type="submit" class="b bp"><i class="fas fa-save"></i> Enregistrer</button><button type="button" class="b bs" id="cancel">Annuler</button></div></form></div></div>';
  C.querySelector('#back').onclick=()=>nav('clients');
  C.querySelector('#cancel').onclick=()=>nav('clients');
  C.querySelector('#clf').onsubmit=function(e){
    e.preventDefault();const f=new FormData(this);const d=Object.fromEntries(f);let a=gd(K.cl);
    if(id){a=a.map(x=>x.id===id?{...x,...d}:x);toast('Modifie','success')}else{a.push({id:uid(),...d,dateCreation:td()});toast('Cree','success')}
    sd(K.cl,a);nav('clients');
  };
}
function rClV(C,id){
  const c=gd(K.cl).find(x=>x.id===id);if(!c){C.innerHTML='<div class="es">Introuvable</div>';return}
  const dv=gd(K.dv).filter(d=>d.clientId===id),fc=gd(K.fc).filter(f=>f.clientId===id);
  document.getElementById('ptitle').textContent=c.nom;
  C.innerHTML='<button class="b bs mb-4" onclick="nav(\'clients\')"><i class="fas fa-arrow-left"></i> Retour</button><div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="cd lg:col-span-1"><div class="text-center mb-4"><div class="w-16 h-16 rounded-full bg-accent/10 flex items-center justify-center mx-auto mb-3 text-2xl font-bold text-accent">'+(c.nom||'?')[0].toUpperCase()+'</div><h2 class="text-xl font-bold">'+c.nom+'</h2><div class="text-muted text-sm">'+(c.entreprise||'')+'</div></div><div class="space-y-3 text-sm"><div class="flex gap-3"><i class="fas fa-envelope text-muted w-5 text-center"></i>'+(c.email||'-')+'</div><div class="flex gap-3"><i class="fas fa-phone text-muted w-5 text-center"></i>'+(c.tel||'-')+'</div><div class="flex gap-3"><i class="fas fa-map-marker-alt text-muted w-5 text-center"></i>'+(c.adresse||'-')+'</div></div>'+(c.notes?'<div class="mt-4 p-3 bg-surface2 rounded-lg text-sm text-muted">'+c.notes+'</div>':'')+'<div class="flex gap-2 mt-4"><button class="b bs sm flex-1" onclick="rClF(\''+id+'\')"><i class="fas fa-pen"></i> Modifier</button><button class="b bd sm" onclick="cfm(\'Supprimer ?\',\'\',function(){sd(K.cl,gd(K.cl).filter(x=>x.id!==\''+id+'\'));toast(\'Supprime\',\'success\');render()})"><i class="fas fa-trash"></i></button></div></div><div class="lg:col-span-2 space-y-6"><div class="cd"><h3 class="font-semibold mb-3">Devis ('+dv.length+')</h3>'+(dv.length?'<table><thead><tr><th>Numero</th><th>Date</th><th>Montant</th><th>Statut</th></tr></thead><tbody>'+dv.map(d=>'<tr class="cursor-pointer" onclick="nav(\'devis\',{id:\''+d.id+'\'})"><td class="font-mono text-accent text-xs">'+d.numero+'</td><td class="text-muted text-sm">'+fd(d.date)+'</td><td>'+fm(d.totalTTC,d.devise)+'</td><td>'+bsg(d.statut,'devis')+'</td></tr>').join('')+'</tbody></table>':'<p class="text-muted text-sm">Aucun</p>')+'</div><div class="cd"><h3 class="font-semibold mb-3">Factures ('+fc.length+')</h3>'+(fc.length?'<table><thead><tr><th>Numero</th><th>Date</th><th>Montant</th><th>Statut</th></tr></thead><tbody>'+fc.map(f=>'<tr class="cursor-pointer" onclick="nav(\'factures\',{id:\''+f.id+'\'})"><td class="font-mono text-accent text-xs">'+f.numero+'</td><td class="text-muted text-sm">'+fd(f.date)+'</td><td>'+fm(f.totalTTC,f.devise)+'</td><td>'+bsg(f.statut,'facture')+'</td></tr>').join('')+'</tbody></table>':'<p class="text-muted text-sm">Aucune</p>')+'</div></div></div>';
}
