/* === PORTAIL CLIENT VALIDATION === */
function renderCVal(enc){
  try{const d=JSON.parse(decodeURIComponent(escape(atob(enc))));showP('<div class="min-h-screen flex items-center justify-center p-4" style="background:linear-gradient(135deg,#f8f7f4,#eee9e0)"><div class="pc w-full max-w-2xl"><div class="text-center mb-8"><div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center mx-auto mb-3"><i class="fas fa-check-double text-amber-600 text-xl"></i></div><h1 class="text-2xl font-bold text-gray-900">'+d.n+'</h1><p class="text-gray-500 text-sm mt-1">Merci de valider les points suivants</p></div><div class="space-y-4 mb-8" id="cpp">'+d.p.map(p=>'<div class="border border-gray-200 rounded-xl p-4" data-pid="'+p.id+'"><h3 class="font-semibold text-gray-900 mb-1">'+p.t+'</h3>'+(p.d?'<p class="text-sm text-gray-500 mb-3">'+p.d+'</p>':'<div class="mb-3"></div>')+'<div class="flex gap-2" id="cb_'+p.id+'"><button class="pb ps" onclick="cpV(\''+p.id+'\',\'valide\')"><i class="fas fa-check mr-1"></i> Valider</button><button class="pb pd" onclick="cpV(\''+p.id+'\',\'rejete\')"><i class="fas fa-times mr-1"></i> Rejeter</button></div><div id="cs_'+p.id+'" class="hidden mt-2 text-sm font-medium"></div></div>').join('')+'</div><div class="mb-6"><label class="block text-sm font-medium text-gray-700 mb-1">Votre nom *</label><input class="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-400" id="cpn" placeholder="Votre nom complet"></div><div id="cpr" class="hidden mb-4 p-4 bg-green-50 border border-green-200 rounded-xl"><p class="text-sm text-green-800 mb-2 font-semibold">Reponse generee ! Copiez ce lien :</p><input class="w-full border border-green-300 rounded-lg px-3 py-2 text-xs font-mono text-green-900 bg-white" id="cprl" readonly onclick="this.select()"><button class="pb ps mt-2" onclick="navigator.clipboard.writeText(document.getElementById(\'cprl\').value);this.textContent=\'Copie !\'"><i class="fas fa-copy mr-1"></i> Copier</button></div><button class="pb pa w-full" id="cps" onclick="cpSub(\''+enc+'\')"><i class="fas fa-paper-plane mr-2"></i> Confirmer et generer la reponse</button></div></div>');window._cpC={}}catch(e){document.body.innerHTML='<p style="padding:40px;color:red">Lien invalide.</p>'}
}
function cpV(pid,st){window._cpC[pid]=st;document.getElementById('cb_'+pid).style.display='none';const el=document.getElementById('cs_'+pid);el.classList.remove('hidden');el.innerHTML=st==='valide'?'<span style="color:#2ECC71"><i class="fas fa-check-circle"></i> Valide</span>':'<span style="color:#E74C3C"><i class="fas fa-times-circle"></i> Rejete</span>'}
function cpSub(enc){const nm=document.getElementById('cpn').value.trim();if(!nm){alert('Entrez votre nom');return}const d=JSON.parse(decodeURIComponent(escape(atob(enc))));const r=d.p.map(p=>({id:p.id,s:window._cpC[p.id]||'en_attente',n:nm,d:new Date().toISOString()}));const pl=btoa(unescape(encodeURIComponent(JSON.stringify({v:d.v,r:r}))));const url=location.origin+location.pathname+'#resp='+pl;document.getElementById('cpr').classList.remove('hidden');document.getElementById('cprl').value=url;document.getElementById('cps').style.display='none';document.getElementById('cpr').scrollIntoView({behavior:'smooth'})}

/* === PORTAIL CLIENT SIGNATURE === */
function renderCSig(enc){
  try{const d=JSON.parse(decodeURIComponent(escape(atob(enc))));showP('<div class="min-h-screen flex items-center justify-center p-4" style="background:linear-gradient(135deg,#f8f7f4,#eee9e0)"><div class="pc w-full max-w-lg"><div class="text-center mb-6"><div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center mx-auto mb-3"><i class="fas fa-signature text-amber-600 text-xl"></i></div><h1 class="text-2xl font-bold text-gray-900">Signature</h1><p class="text-gray-500 text-sm mt-1">Pour : '+d.n+'</p></div><div class="border-2 border-dashed border-gray-300 rounded-xl overflow-hidden mb-4 bg-white relative"><canvas id="cscv" width="500" height="200" class="w-full cursor-crosshair" style="touch-action:none"></canvas><div id="csph" class="absolute inset-0 flex items-center justify-center text-gray-400 text-sm pointer-events-none">Signez ici</div></div><div class="flex gap-3 mb-4"><button class="pb po flex-1" onclick="document.getElementById(\'cscv\').getContext(\'2d\').clearRect(0,0,500,200);document.getElementById(\'csph\').style.display=\'flex\'">Effacer</button><button class="pb pa flex-1" onclick="cpSS(\''+enc+'\')">Signer</button></div><div id="cssr" class="hidden p-4 bg-green-50 border border-green-200 rounded-xl"><p class="text-sm text-green-800 mb-2 font-semibold">Signature enregistree ! Copiez ce lien :</p><input class="w-full border border-green-300 rounded-lg px-3 py-2 text-xs font-mono text-green-900 bg-white" id="cssrl" readonly onclick="this.select()"><button class="pb ps mt-2" onclick="navigator.clipboard.writeText(document.getElementById(\'cssrl\').value)"><i class="fas fa-copy mr-1"></i> Copier</button></div></div></div>');const cv=document.getElementById('cscv');const cx=cv.getContext('2d');cx.strokeStyle='#1a1a1a';cx.lineWidth=2.5;cx.lineCap='round';cx.lineJoin='round';let dr=false;const gp=e=>{const r=cv.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*(cv.width/r.width),y:(t.clientY-r.top)*(cv.height/r.height)}};cv.onmousedown=e=>{dr=true;const p=gp(e);cx.beginPath();cx.moveTo(p.x,p.y);document.getElementById('csph').style.display='none'};cv.onmousemove=e=>{if(!dr)return;const p=gp(e);cx.lineTo(p.x,p.y);cx.stroke()};cv.onmouseup=cv.onmouseleave=()=>dr=false;cv.ontouchstart=e=>{e.preventDefault();dr=true;const p=gp(e);cx.beginPath();cx.moveTo(p.x,p.y);document.getElementById('csph').style.display='none'};cv.ontouchmove=e=>{if(!dr)return;e.preventDefault();const p=gp(e);cx.lineTo(p.x,p.y);cx.stroke()};cv.ontouchend=()=>dr=false}catch(e){document.body.innerHTML='<p style="padding:40px;color:red">Lien invalide.</p>'}
}
function cpSS(enc){const cv=document.getElementById('cscv');const bk=document.createElement('canvas');bk.width=cv.width;bk.height=cv.height;if(cv.toDataURL()===bk.toDataURL()){alert('Signez d\'abord');return}const d=JSON.parse(decodeURIComponent(escape(atob(enc))));const pl=btoa(unescape(encodeURIComponent(JSON.stringify({c:d.c,s:cv.toDataURL('image/jpeg',0.7)}))));const url=location.origin+location.pathname+'#sigresp='+pl;document.getElementById('cssr').classList.remove('hidden');document.getElementById('cssrl').value=url;cv.parentElement.parentElement.querySelector('.flex.gap-3').style.display='none';document.getElementById('cssr').scrollIntoView({behavior:'smooth'})}
function importSResp(enc){showM('Importer une signature','<p class="text-sm text-muted mb-3">Collez le lien de signature :</p><input class="ip font-mono text-xs mb-4" id="sri" value="#sigresp='+enc+'"><div class="flex gap-3 justify-end"><button class="b bs" onclick="closeM()">Annuler</button><button class="b bp" onclick="procSR()">Importer</button></div>')}
function procSR(){let v=document.getElementById('sri').value.trim();if(v.includes('#sigresp='))v=v.split('#sigresp=')[1];try{const d=JSON.parse(decodeURIComponent(escape(atob(v))));const s=gs(K.sg);s[d.c]=d.s;ss(K.sg,s);closeM();toast('Signature importee !','success');if(pg==='signature')rSig(document.getElementById('ct'))}catch(e){toast('Lien invalide','error')}}
