/* === RETROPLANNING === */
function rRt(C){
  const a=gd(K.rt),cl=gd(K.cl);
  C.innerHTML='<div class="flex items-center justify-between mb-6"><span class="text-muted text-sm">'+a.length+' retroplanning(s)</span><button class="b bp" onclick="rRtF()"><i class="fas fa-plus"></i> Nouveau</button></div>'+(a.length?'<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">'+a.map(r=>{const c=cl.find(x=>x.id===r.clientId);const dn=r.etapes.filter(e=>e.statut==='termine').length;const pc=r.etapes.length?Math.round(dn/r.etapes.length*100):0;return'<div class="cd cursor-pointer hover:border-accent/30 transition-colors" onclick="nav(\'retroplanning\',{id:\''+r.id+'\'})"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold">'+r.nom+'</h3><button class="b bd sm" onclick="event.stopPropagation();cfm(\'Supprimer ?\',\'\',function(){sd(K.rt,gd(K.rt).filter(x=>x.id!==\''+r.id+'\'));toast(\'Supprime\',\'success\');render()})"><i class="fas fa-trash"></i></button></div><div class="text-sm text-muted mb-3"><i class="fas fa-user mr-2"></i>'+(c?.nom||'-')+'<br><i class="fas fa-list-check mr-2"></i>'+r.etapes.length+' etapes</div><div class="w-full bg-surface2 rounded-full h-2"><div class="bg-accent h-2 rounded-full" style="width:'+pc+'%"></div></div><div class="text-right text-xs text-muted mt-1">'+pc+'%</div></div>'}).join('')+'</div>':'<div class="cd es"><i class="fas fa-calendar-alt block"></i>Aucun retroplanning.</div>');
}
function rRtF(id){
  const r=id?gd(K.rt).find(x=>x.id===id):null;const cl=gd(K.cl);
  document.getElementById('ptitle').textContent=r?'Modifier le retroplanning':'Nouveau retroplanning';
  const C=document.getElementById('ct');const et=r?r.etapes:[{id:uid(),nom:'',dateDebut:'',dateFin:'',statut:'a_venir'}];
  C.innerHTML='<div class="max-w-3xl"><button class="b bs mb-4" onclick="nav(\'retroplanning\')"><i class="fas fa-arrow-left"></i> Retour</button><div class="cd"><form id="rtf"><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6"><div><label>Client *</label><select class="ip" name="clientId" required><option value="">Selectionner...</option>'+cl.map(c=>'<option value="'+c.id+'" '+(r?.clientId===c.id?'selected':'')+'>'+c.nom+'</option>').join('')+'</select></div><div><label>Nom du projet *</label><input class="ip" name="nom" required value="'+(r?.nom||'')+'"></div></div><div class="mb-4"><div class="flex items-center justify-between mb-3"><label class="mb-0">Etapes</label><button type="button" class="b bs sm" onclick="addEt()"><i class="fas fa-plus"></i> Ajouter</button></div><div id="etc" class="space-y-3">'+et.map((e,i)=>etH(e,i)).join('')+'</div></div><div class="flex gap-3 mt-6"><button type="submit" class="b bp"><i class="fas fa-save"></i> Enregistrer</button><button type="button" class="b bs" onclick="nav(\'retroplanning\')">Annuler</button></div></form></div></div>';
  C.querySelector('#rtf').onsubmit=function(e){
    e.preventDefault();const f=new FormData(this);const et=[];let i=0;
    while(document.querySelector('[name="en'+i+'"]')){et.push({id:uid(),nom:f.get('en'+i),dateDebut:f.get('ed'+i),dateFin:f.get('ef'+i),statut:f.get('es'+i)});i++}
    const data={clientId:f.get('clientId'),nom:f.get('nom'),etapes:et};let a=gd(K.rt);
    if(id){a=a.map(x=>x.id===id?{...x,...data}:x);toast('Modifie','success')}else{a.push({id:uid(),...data});toast('Cree','success')}
    sd(K.rt,a);nav('retroplanning');
  };
}
function etH(e,i){return'<div class="p-4 bg-surface2 rounded-lg etr" data-i="'+i+'"><div class="grid grid-cols-1 md:grid-cols-4 gap-3"><input class="ip" name="en'+i+'" placeholder="Nom" value="'+(e.nom||'').replace(/"/g,'&quot;')+'"><input class="ip" name="ed'+i+'" type="date" value="'+(e.dateDebut||'')+'"><input class="ip" name="ef'+i+'" type="date" value="'+(e.dateFin||'')+'"><select class="ip" name="es'+i+'"><option value="a_venir" '+(e.statut==='a_venir'?'selected':'')+'>A venir</option><option value="en_cours" '+(e.statut==='en_cours'?'selected':'')+'>En cours</option><option value="termine" '+(e.statut==='termine'?'selected':'')+'>Termine</option></select></div><button type="button" class="b bd sm mt-2" onclick="this.closest(\'.etr\').remove()"><i class="fas fa-times"></i> Supprimer</button></div>'}
function addEt(){const c=document.getElementById('etc');c.insertAdjacentHTML('beforeend',etH({id:uid(),nom:'',dateDebut:'',dateFin:'',statut:'a_venir'},c.children.length))}
function rRtV(C,id){
  const r=gd(K.rt).find(x=>x.id===id),cl=gd(K.cl);if(!r){C.innerHTML='<div class="es">Introuvable</div>';return}
  const c=cl.find(x=>x.id===r.clientId);document.getElementById('ptitle').textContent=r.nom;
  const ds=r.etapes.map(e=>[e.dateDebut,e.dateFin].filter(Boolean).map(d=>new Date(d).getTime())).flat();
  const mn=ds.length?Math.min(...ds):Date.now(),mx=ds.length?Math.max(...ds):Date.now()+864e5,rng=Math.max(mx-mn,864e5);
  const co={a_venir:'background:rgba(107,112,137,.15);border:1px solid rgba(107,112,137,.3);color:#6B7089',en_cours:'background:rgba(52,152,219,.15);border:1px solid rgba(52,152,219,.3);color:#3498DB',termine:'background:rgba(46,204,113,.15);border:1px solid rgba(46,204,113,.3);color:#2ECC71'};
  C.innerHTML='<button class="b bs mb-4" onclick="nav(\'retroplanning\')"><i class="fas fa-arrow-left"></i> Retour</button><div class="flex flex-wrap gap-2 mb-4"><button class="b bs" onclick="rRtF(\''+id+'\')"><i class="fas fa-pen"></i> Modifier</button></div><div class="cd mb-6"><div class="text-sm"><span class="text-muted">Client :</span> <strong>'+(c?.nom||'-')+'</strong> — <span class="text-muted">'+r.etapes.length+' etapes</span></div></div><div class="cd overflow-x-auto"><div style="min-width:700px">'+r.etapes.map(e=>{const s=e.dateDebut?new Date(e.dateDebut).getTime():mn,en=e.dateFin?new Date(e.dateFin).getTime():s+864e5*3,l=Math.max(0,((s-mn)/rng)*100),w=Math.max(3,((en-s)/rng)*100);return'<div class="flex items-center gap-4 mb-3" style="min-height:40px"><div class="w-48 flex-shrink-0 text-sm font-medium truncate">'+(e.nom||'Etape')+'</div><div class="flex-1 relative h-10"><div class="gb" style="left:'+l+'%;width:'+w+'%;'+(co[e.statut]||'')+'">'+(e.nom||'')+'</div></div><select class="ip w-28 text-xs py-1" onchange="sd(K.rt,gd(K.rt).map(r=>r.id===\''+id+'\'?{...r,etapes:r.etapes.map(x=>x.id===\''+e.id+'\'?{...x,statut:this.value}:x)}:r));toast(\'OK\',\'success\');render()"><option value="a_venir" '+(e.statut==='a_venir'?'selected':'')+'>A venir</option><option value="en_cours" '+(e.statut==='en_cours'?'selected':'')+'>En cours</option><option value="termine" '+(e.statut==='termine'?'selected':'')+'>Termine</option></select></div>'}).join('')+'</div></div>';
}
