/* === SIGNATURES === */
function rSig(C){
  const cl=gd(K.cl),sg=gs(K.sg);const en=Object.entries(sg);
  C.innerHTML='<div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="cd"><h3 class="font-semibold mb-4">Capturer une signature</h3><div class="mb-4"><label>Client</label><select class="ip" id="scl"><option value="">Selectionner...</option>'+cl.map(c=>'<option value="'+c.id+'">'+c.nom+'</option>').join('')+'</select></div><div class="border-2 border-dashed border-border rounded-xl overflow-hidden mb-4 bg-surface2 relative"><canvas id="scv" width="500" height="200" class="w-full cursor-crosshair" style="touch-action:none"></canvas><div id="sph" class="absolute inset-0 flex items-center justify-center text-muted text-sm pointer-events-none">Signez ici</div></div><div class="flex gap-3"><button class="b bs" id="sclr"><i class="fas fa-eraser"></i> Effacer</button><button class="b bp" id="ssav"><i class="fas fa-save"></i> Enregistrer</button></div></div><div class="cd"><h3 class="font-semibold mb-4">Signatures ('+en.length+')</h3>'+(en.length?'<div class="space-y-3">'+en.map(([cid,sig])=>{const c=cl.find(x=>x.id===cid);return'<div class="flex items-center justify-between p-3 bg-surface2 rounded-lg"><div class="flex items-center gap-3"><img src="'+sig+'" class="h-12 bg-white rounded p-1"><div><div class="text-sm font-medium">'+(c?.nom||'Inconnu')+'</div><div class="text-xs text-muted">'+(c?.entreprise||'')+'</div></div></div><div class="flex gap-2"><button class="b bs sm" onclick="genSL(\''+cid+'\')"><i class="fas fa-link"></i></button><button class="b bd sm" onclick="delS(\''+cid+'\')"><i class="fas fa-trash"></i></button></div></div>'}).join('')+'</div>':'<div class="text-muted text-sm text-center py-8">Aucune signature</div>')+'</div></div>';
  initSC();
  C.querySelector('#sclr').onclick=()=>{const cv=document.getElementById('scv');cv.getContext('2d').clearRect(0,0,cv.width,cv.height);document.getElementById('sph').style.display='flex'};
  C.querySelector('#ssav').onclick=()=>{const cid=document.getElementById('scl').value;if(!cid){toast('Selectionnez un client','error');return}const cv=document.getElementById('scv');const bk=document.createElement('canvas');bk.width=cv.width;bk.height=cv.height;if(cv.toDataURL()===bk.toDataURL()){toast('Signez d\'abord','error');return}const s=gs(K.sg);s[cid]=cv.toDataURL('image/jpeg',0.7);ss(K.sg,s);toast('Signature enregistree','success');rSig(C)};
}
function initSC(){const cv=document.getElementById('scv');if(!cv)return;const cx=cv.getContext('2d');cx.strokeStyle='#E8A832';cx.lineWidth=2.5;cx.lineCap='round';cx.lineJoin='round';let dr=false;const gp=e=>{const r=cv.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*(cv.width/r.width),y:(t.clientY-r.top)*(cv.height/r.height)}};const st=e=>{e.preventDefault();dr=true;const p=gp(e);cx.beginPath();cx.moveTo(p.x,p.y);document.getElementById('sph').style.display='none'};const mv=e=>{if(!dr)return;e.preventDefault();const p=gp(e);cx.lineTo(p.x,p.y);cx.stroke()};const ed=()=>dr=false;cv.onmousedown=st;cv.onmousemove=mv;cv.onmouseup=ed;cv.onmouseleave=ed;cv.ontouchstart=st;cv.ontouchmove=mv;cv.ontouchend=ed}
function delS(cid){const s=gs(K.sg);delete s[cid];ss(K.sg,s);toast('Supprimee','success');rSig(document.getElementById('ct'))}
function genSL(cid){const cl=gd(K.cl);const c=cl.find(x=>x.id===cid);if(!c)return;const pl=btoa(unescape(encodeURIComponent(JSON.stringify({c:cid,n:c.nom}))));const url=location.origin+location.pathname+'#sign='+pl;showM('Lien de signature','<p class="text-sm text-muted mb-3">Envoyez ce lien a <strong>'+c.nom+'</strong> :</p><input class="ip font-mono text-xs" value="'+url+'" readonly onclick="this.select()" id="sli"><div class="flex gap-2 mt-4"><button class="b bp sm" onclick="navigator.clipboard.writeText(document.getElementById(\'sli\').value);toast(\'Copie\',\'success\')"><i class="fas fa-copy"></i> Copier</button></div>')}
