/* === VALIDATIONS === */
function rVl(C){
  const a=gd(K.vl),cl=gd(K.cl);
  C.innerHTML='<div class="flex items-center justify-between mb-6"><span class="text-muted text-sm">'+a.length+' projet(s)</span><button class="b bp" onclick="rVlF()"><i class="fas fa-plus"></i> Nouveau</button></div>'+(a.length?'<div class="space-y-4">'+a.map(v=>{const c=cl.find(x=>x.id===v.clientId);const at=v.points.filter(p=>p.statut==='en_attente').length,ok=v.points.filter(p=>p.statut==='valide').length,ko=v.points.filter(p=>p.statut==='rejete').length;return'<div class="cd"><div class="flex flex-col md:flex-row md:items-center justify-between gap-4"><div class="flex-1"><h3 class="font-semibold text-lg">'+v.projetNom+'</h3><div class="text-sm text-muted mb-2"><i class="fas fa-user mr-1"></i>'+(c?.nom||'-')+'</div><div class="flex gap-4 text-sm"><span class="badge bw">'+at+' en attente</span><span class="badge bo">'+ok+' valide(s)</span><span class="badge bk">'+ko+' rejete(s)</span></div></div><div class="flex gap-2 flex-wrap"><button class="b bp sm" onclick="genVL(\''+v.id+'\')"><i class="fas fa-link"></i> Lien client</button><button class="b bs sm" onclick="impVR()"><i class="fas fa-download"></i> Importer</button><button class="b bs sm" onclick="nav(\'validation\',{id:\''+v.id+'\'})"><i class="fas fa-eye"></i> Detail</button><button class="b bd sm" onclick="cfm(\'Supprimer ?\',\'\',function(){sd(K.vl,gd(K.vl).filter(x=>x.id!==\''+v.id+'\'));toast(\'Supprime\',\'success\');render()})"><i class="fas fa-trash"></i></button></div></div></div>'}).join('')+'</div>':'<div class="cd es"><i class="fas fa-check-double block"></i>Aucun projet.</div>');
}
function rVlF(id){
  const v=id?gd(K.vl).find(x=>x.id===id):null;const cl=gd(K.cl);
  document.getElementById('ptitle').textContent=v?'Modifier':'Nouveau projet de validation';
  const C=document.getElementById('ct');const pts=v?v.points:[{id:uid(),titre:'',description:'',statut:'en_attente',validePar:'',dateValidation:''}];
  C.innerHTML='<div class="max-w-3xl"><button class="b bs mb-4" onclick="nav(\'validation\')"><i class="fas fa-arrow-left"></i> Retour</button><div class="cd"><form id="vlf"><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6"><div><label>Client *</label><select class="ip" name="clientId" required><option value="">Selectionner...</option>'+cl.map(c=>'<option value="'+c.id+'" '+(v?.clientId===c.id?'selected':'')+'>'+c.nom+'</option>').join('')+'</select></div><div><label>Nom du projet *</label><input class="ip" name="projetNom" required value="'+(v?.projetNom||'')+'"></div></div><div class="mb-4"><div class="flex items-center justify-between mb-3"><label class="mb-0">Points a valider</label><button type="button" class="b bs sm" onclick="addPt()"><i class="fas fa-plus"></i> Ajouter</button></div><div id="ptc" class="space-y-3">'+pts.map((p,i)=>ptH(p,i)).join('')+'</div></div><div class="flex gap-3 mt-6"><button type="submit" class="b bp"><i class="fas fa-save"></i> Enregistrer</button><button type="button" class="b bs" onclick="nav(\'validation\')">Annuler</button></div></form></div></div>';
  C.querySelector('#vlf').onsubmit=function(e){
    e.preventDefault();const f=new FormData(this);const pts=[];let i=0;
    while(document.querySelector('[name="pt'+i+'"]')){const t=f.get('pt'+i);if(t)pts.push({id:uid(),titre:t,description:f.get('pd'+i),statut:'en_attente',validePar:'',dateValidation:''});i++}
    const data={clientId:f.get('clientId'),projetNom:f.get('projetNom'),points:pts};let a=gd(K.vl);
    if(id){const old=a.find(x=>x.id===id);a=a.map(x=>x.id===id?{...x,...data,points:data.points.map((p,j)=>({...p,...(old?.points[j]||{}),titre:p.titre,description:p.description}))}:x);toast('Modifie','success')}else{a.push({id:uid(),...data});toast('Cree','success')}
    sd(K.vl,a);nav('validation');
  };
}
function ptH(p,i){return'<div class="p-4 bg-surface2 rounded-lg ptr" data-i="'+i+'"><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><input class="ip" name="pt'+i+'" placeholder="Titre du point" value="'+(p.titre||'').replace(/"/g,'&quot;')+'"><input class="ip" name="pd'+i+'" placeholder="Description (optionnel)" value="'+(p.description||'').replace(/"/g,'&quot;')+'"></div><button type="button" class="b bd sm mt-2" onclick="this.closest(\'.ptr\').remove()"><i class="fas fa-times"></i> Supprimer</button></div>'}
function addPt(){const c=document.getElementById('ptc');c.insertAdjacentHTML('beforeend',ptH({id:uid(),titre:'',description:'',statut:'en_attente'},c.children.length))}
function rVlV(C,id){
  const v=gd(K.vl).find(x=>x.id===id),cl=gd(K.cl);if(!v){C.innerHTML='<div class="es">Introuvable</div>';return}
  const c=cl.find(x=>x.id===v.clientId);document.getElementById('ptitle').textContent=v.projetNom;
  const si={en_attente:'fa-clock text-warning',valide:'fa-check-circle text-success',rejete:'fa-times-circle text-danger'};
  const sl={en_attente:'En attente',valide:'Valide',rejete:'Rejete'};
  const bc={en_attente:'bw',valide:'bo',rejete:'bk'};
  C.innerHTML='<button class="b bs mb-4" onclick="nav(\'validation\')"><i class="fas fa-arrow-left"></i> Retour</button><div class="flex flex-wrap gap-2 mb-6"><button class="b bp" onclick="genVL(\''+id+'\')"><i class="fas fa-link"></i> Generer le lien client</button><button class="b bs" onclick="impVR()"><i class="fas fa-download"></i> Importer une reponse</button><button class="b bs" onclick="rVlF(\''+id+'\')"><i class="fas fa-pen"></i> Modifier</button></div><div class="cd mb-4"><div class="text-sm text-muted">Client : <strong class="text-fg">'+(c?.nom||'-')+'</strong></div></div><div class="space-y-3">'+v.points.map(p=>'<div class="cd flex flex-col md:flex-row md:items-center justify-between gap-3"><div class="flex-1"><div class="flex items-center gap-2 mb-1"><i class="fas '+si[p.statut]+'"></i><h4 class="font-semibold">'+p.titre+'</h4></div>'+(p.description?'<p class="text-sm text-muted">'+p.description+'</p>':'')+'</div><div class="flex items-center gap-3"><span class="badge '+bc[p.statut]+'">'+sl[p.statut]+'</span>'+(p.validePar?'<div class="text-right text-xs text-muted"><div>par '+p.validePar+'</div><div>'+(p.dateValidation?new Date(p.dateValidation).toLocaleString('fr-FR'):'')+'</div></div>':'')+'</div></div>').join('')+'</div>';
}
function genVL(vid){
  const v=gd(K.vl).find(x=>x.id===vid);if(!v)return;
  const pl=btoa(unescape(encodeURIComponent(JSON.stringify({v:vid,n:v.projetNom,p:v.points.map(p=>({id:p.id,t:p.titre,d:p.description}))}))));
  const url=location.origin+location.pathname+'#val='+pl;
  showM('Lien de validation','<p class="text-sm text-muted mb-3">Envoyez ce lien au client :</p><input class="ip font-mono text-xs mb-3" value="'+url+'" readonly onclick="this.select()" id="vli"><div class="flex gap-2"><button class="b bp sm" onclick="navigator.clipboard.writeText(document.getElementById(\'vli\').value);toast(\'Copie\',\'success\')"><i class="fas fa-copy"></i> Copier</button></div><div class="mt-4 p-3 bg-surface2 rounded-lg text-xs text-muted"><strong>Processus :</strong><ol class="list-decimal ml-4 mt-1 space-y-1"><li>Envoyez le lien au client</li><li>Il valide/rejette les points</li><li>Il vous renvoie le lien de reponse</li><li>Cliquez "Importer une reponse" et collez le lien</li></ol></div>');
}
function impVR(){showM('Importer une reponse','<p class="text-sm text-muted mb-3">Collez le lien de reponse du client :</p><input class="ip font-mono text-xs mb-4" id="ri"><div class="flex gap-3 justify-end"><button class="b bs" onclick="closeM()">Annuler</button><button class="b bp" onclick="procVR()">Importer</button></div>')}
function importVResp(enc){impVR();setTimeout(()=>{const i=document.getElementById('ri');if(i)i.value='#resp='+enc},100)}
function procVR(){let v=document.getElementById('ri').value.trim();if(v.includes('#resp='))v=v.split('#resp=')[1];try{const d=JSON.parse(decodeURIComponent(escape(atob(v))));const a=gd(K.vl);const i=a.findIndex(x=>x.id===d.v);if(i===-1){toast('Projet introuvable','error');return}d.r.forEach(r=>{const pi=a[i].points.findIndex(p=>p.id===r.id);if(pi!==-1){a[i].points[pi].statut=r.s;a[i].points[pi].validePar=r.n;a[i].points[pi].dateValidation=r.d}});sd(K.vl,a);closeM();toast('Reponse importee !','success');render()}catch(e){toast('Lien invalide','error')}}
